### ISSUE TITLE
`create` fails on Window

### ISSUE THREAD

**Issue by IniZio** [clippedjs/clipped#119]
```
C:\source
λ npm i -g clipped@2.1.4
C:\Users\Mark\AppData\Roaming\npm\clipped -> C:\Users\Mark\AppData\Roaming\npm\node_modules\clipped\bin\clipped
+ clipped@2.1.4
updated 1 package in 15.395s
```
then:

```
C:\source
λ cd clipTest\

C:\source\clipTest
λ clipped init

Usage:    clipped ACTION

Actions:
version, create, config:watch


C:\source\clipTest
λ clipped create
{ Error: spawn npm ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:362:16)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn npm',
  path: 'npm',
  spawnargs: [ 'init' ] }

C:\source\clipTest
λ ls

C:\source\clipTest
λ clipped

Usage:    clipped ACTION

Actions:
version, create, config:watch


C:\source\clipTest
λ clipped create
{ Error: spawn npm ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:362:16)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn npm',
  path: 'npm',
  spawnargs: [ 'init' ] }

C:\source\clipTest
λ clipped version
2.1.4

```

_Originally posted by @devtech8 in https://github.com/clippedjs/clipped/issues/118#issuecomment-435570029_

**Comment by IniZio** [comment]
@devtech8 could you try clipped v2.1.4-patch1? If it solves the issue I will merge #120 and release v2.1.5 for the bug fix

**Comment by devtech8** [comment]
@IniZio  - it seems somewhat fixed in that you can run `clipped init` and `clipped create`.  **Additionally, please read my comment below this long paste of code:**

```
C:\source\clipTest                                                                                                      
λ npm i -g clipped@2.1.4-patch1                                                                                         
C:\Users\Mark\AppData\Roaming\npm\clipped -> C:\Users\Mark\AppData\Roaming\npm\node_modules\clipped\bin\clipped         
+ clipped@2.1.4-patch1                                                                                                  
added 1 package from 1 contributor, removed 2 packages and updated 3 packages in 18.345s                                
                                                                                                                        
C:\source\clipTest                                                                                                      
λ clipped version                                                                                                       
2.1.4-patch1                                                                                                            
                                                                                                                        
                                                                                                                        
C:\source\clipTest                                                                                                      
λ clipped init                                                                                                          
                                                                                                                        
Usage:    clipped ACTION                                                                                                
                                                                                                                        
Actions:                                                                                                                
version, create, config:watch                                                                                           
                                                                                                                        
                                                                                                                        
C:\source\clipTest                                                                                                      
λ clipped create                                                                                                        
This utility will walk you through creating a package.json file.                                                        
It only covers the most common items, and tries to guess sensible defaults.                                             
                                                                                                                        
See `npm help json` for definitive documentation on these fields                                                        
and exactly what they do.                                                                                               
                                                                                                                        
Use `npm install <pkg>` afterwards to install a package and                                                             
save it as a dependency in the package.json file.                                                                       
                                                                                                                        
Press ^C at any time to quit.                                                                                           
package name: (cliptest)                                                                                                
version: (1.0.0)                                                                                                        
description: testing 2.1.4-patch1 on windows 10 box                                                                     
entry point: (index.js)                                                                                                 
test command: testit                                                                                                    
git repository:                                                                                                         
keywords: testing clipped patch                                                                                         
author: m. godfrey                                                                                                      
license: (ISC)                                                                                                          
About to write to C:\source\clipTest\package.json:                                                                      
                                                                                                                        
{                                                                                                                       
  "name": "cliptest",                                                                                                   
  "version": "1.0.0",                                                                                                   
  "description": "testing 2.1.4-patch1 on windows 10 box",                                                              
  "main": "index.js",                                                                                                   
  "scripts": {                                                                                                          
    "test": "testit"                                                                                                    
  },                                                                                                                    
  "keywords": [                                                                                                         
    "testing",                                                                                                          
    "clipped",                                                                                                          
    "patch"                                                                                                             
  ],                                                                                                                    
  "author": "m. godfrey",                                                                                               
  "license": "ISC"                                                                                                      
}                                                                                                                       
                                                                                                                        
                                                                                                                        
Is this OK? (yes)                                                                                                       
√ Pick your packages » @clipped/template-react, @clipped/plugin-webpack                                                 
[ '@clipped/template-react', '@clipped/plugin-webpack' ]                                                                
npm notice created a lockfile as package-lock.json. You should commit this file.                                        
npm WARN html-webpack-template@6.2.0 requires a peer of html-webpack-plugin@2.x || ^3 but none is installed. You must in
stall peer dependencies yourself.                                                                                       
npm WARN babel-loader@8.0.4 requires a peer of @babel/core@^7.0.0 but none is installed. You must install peer dependenc
ies yourself.                                                                                                           
npm WARN @babel/preset-react@7.0.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer 
dependencies yourself.                                                                                                  
npm WARN react-hot-loader@4.3.12 requires a peer of react@^15.0.0 || ^16.0.0 but none is installed. You must install pee
r dependencies yourself.                                                                                                
npm WARN @babel/plugin-transform-react-jsx-self@7.0.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You
 must install peer dependencies yourself.                                                                               
npm WARN @babel/plugin-transform-react-jsx-source@7.0.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. Y
ou must install peer dependencies yourself.                                                                             
npm WARN @babel/plugin-transform-react-display-name@7.0.0 requires a peer of @babel/core@^7.0.0-0 but none is installed.
 You must install peer dependencies yourself.                                                                           
npm WARN @babel/plugin-transform-react-jsx@7.0.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must
 install peer dependencies yourself.                                                                                    
npm WARN @babel/plugin-syntax-jsx@7.0.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install 
peer dependencies yourself.                                                                                             
npm WARN cliptest@1.0.0 No repository field.                                                                            
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):                                 
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any
"} (current: {"os":"win32","arch":"x64"})                                                                               
                                                                                                                        
+ @clipped/template-react@1.1.1                                                                                         
+ @clipped/plugin-webpack@1.1.1                                                                                         
added 682 packages from 431 contributors and audited 7980 packages in 34.813s                                           
found 0 vulnerabilities                                                                                                 
                                                                                                                        
npm WARN @babel/plugin-syntax-jsx@7.0.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install 
peer dependencies yourself.                                                                                             
npm WARN @babel/plugin-transform-react-display-name@7.0.0 requires a peer of @babel/core@^7.0.0-0 but none is installed.
 You must install peer dependencies yourself.                                                                           
npm WARN @babel/plugin-transform-react-jsx@7.0.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must
 install peer dependencies yourself.                                                                                    
npm WARN @babel/plugin-transform-react-jsx-self@7.0.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You
 must install peer dependencies yourself.                                                                               
npm WARN @babel/plugin-transform-react-jsx-source@7.0.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. Y
ou must install peer dependencies yourself.                                                                             
npm WARN @babel/preset-react@7.0.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer 
dependencies yourself.                                                                                                  
npm WARN babel-loader@8.0.4 requires a peer of @babel/core@^7.0.0 but none is installed. You must install peer dependenc
ies yourself.                                                                                                           
npm WARN html-webpack-template@6.2.0 requires a peer of html-webpack-plugin@2.x || ^3 but none is installed. You must in
stall peer dependencies yourself.                                                                                       
npm WARN react-hot-loader@4.3.12 requires a peer of react@^15.0.0 || ^16.0.0 but none is installed. You must install pee
r dependencies yourself.                                                                                                
npm WARN cliptest@1.0.0 No repository field.                                                                            
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):                                 
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any
"} (current: {"os":"win32","arch":"x64"})                                                                               
                                                                                                                        
audited 7980 packages in 6.25s                                                                                          
found 0 vulnerabilities               
```                                                                                  

Coming in as a developer to understand how a package like this could help me, I see based on the create prompts that really, no matter what options you select, in essence, all you get is a `package.json`.  Guess based on the links and articles that brought me her to review and see how it works with and/or better than `create-react-app` or CRA.

**Comment by IniZio** [comment]
@devtech8 Good to see the issue resolved, But I also would like to clarify it is not promoting itself as a better create-react-app. create-react-app is more like a boilerplate maintained by Facebook and is really well optimized. However there is not much way you can customize the webpack underneath unless you eject.

For instance, it is generally agreed that Rollup is better than Webpack for creating libraries for React such as ui components. This kind of scenario is not covered by create-react-app at all.

With this library, what you might have noticed in my Medium post is that it is easy to modify the Webpack config. Maybe then you want to build a docker image, then you can use @clipped/plugin-docker. Or maybe you want to use rollup, then you can use @clipped/plugin-rollup.
